//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB6test
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public int NamXB { get; set; }
        public int MaLoai { get; set; }
    
        public virtual LoaiSach LoaiSach { get; set; }
    }
}
